# Generated by Django 2.1 on 2019-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('author', models.CharField(blank=True, max_length=500, verbose_name='作者')),
                ('img', models.CharField(blank=True, max_length=500, verbose_name='封面图')),
                ('tag', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('price', models.FloatField(blank=True, verbose_name='价格')),
                ('publish_month', models.IntegerField(blank=True, verbose_name='出版距今月份')),
                ('click', models.IntegerField(blank=True, verbose_name='点击次数')),
                ('socre', models.FloatField(blank=True, verbose_name='评分')),
                ('judge', models.IntegerField(blank=True, verbose_name='评价人数')),
                ('rec_most', models.IntegerField(blank=True, verbose_name='力荐人数')),
                ('rec_more', models.IntegerField(blank=True, verbose_name='推荐人数')),
                ('rec_normal', models.IntegerField(blank=True, verbose_name='还行人数')),
                ('rec_bad', models.IntegerField(blank=True, verbose_name='较差人数')),
                ('rec_morebad', models.IntegerField(blank=True, verbose_name='很差人数')),
                ('readed', models.IntegerField(blank=True, verbose_name='读过人数')),
                ('reading', models.IntegerField(blank=True, verbose_name='正在读人数')),
                ('readup', models.IntegerField(blank=True, verbose_name='想读人数')),
                ('mess', models.CharField(blank=True, max_length=1000, verbose_name='出版信息')),
            ],
            options={
                'verbose_name_plural': '图书信息',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
            ],
            options={
                'verbose_name_plural': '标签类别',
                'db_table': 'cate',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('time', models.DateTimeField(blank=True, default='2008-12-12 12:12:00', verbose_name='点击时间')),
                ('action', models.CharField(max_length=64, verbose_name='行为')),
                ('object', models.CharField(max_length=64, verbose_name='对象')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '行为信息',
                'db_table': 'history',
            },
        ),
    ]
